=== Papp-Marcell/X7A7XR_XMLGyak/X7A7XR_1012/PM_konyv1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:complexType name="konyvekTipus">
	<xs:sequence>
		<xs:element name="konyv" type="konyvTipus"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="konyvTipus">
	<xs:sequence>
		<xs:element name="cim" type="xs:string"/>
		<xs:element name="szerzo" type="xs:string"/>
		<xs:element name="szereplo" type="szereploTipus" maxOccurs="2"/>
	</xs:sequence>
	<xs:attribute name="isbn" type="xs:positiveInteger"/>
</xs:complexType>

<xs:complexType name="szereploTipus">
	<xs:sequence>
		<xs:element name="nev" type="xs:string"/>
		<xs:element name="baratja" type="xs:string" minOccurs="0"/>
		<xs:element name="szuletett" type="xs:string"/>
		<xs:element name="jellemzes" type="xs:string"/>
	</xs:sequence>
</xs:complexType>

<xs:element name="konyvek" type="konyvekTipus"/>
</xs:schema>

=== Papp-Marcell/X7A7XR_XMLGyak/X7A7XR_1012/PM_konyv1.xml
<?xml version="1.0" encoding="UTF-8"?>
<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PM_konyv1.xsd">
	<konyv isbn="1">
		<cim>kitalált könyv</cim>
		<szerzo>fantázia</szerzo>
		<szereplo>
			<nev>Jancsi</nev>
			<baratja>Feri</baratja>
			<szuletett>tegnap</szuletett>
			<jellemzes>Jancsi</jellemzes>
		</szereplo>
		<szereplo>
			<nev>Feri</nev>
			<szuletett>tegnapelőtt</szuletett>
			<jellemzes>Feri</jellemzes>
		</szereplo>
	</konyv>
</konyvek>
