=== Papp-Marcell/X7A7XR_XMLGyak/XMLTaskX7A7XR/DOMParseX7A7XR/src/hu/domparse/X7A7XR/XMLSchemaX7A7XR.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Adatbazis" type="adatbazis_tipus"/>
	
	<xs:complexType name="adatbazis_tipus">
		<xs:sequence>
			<xs:element name="Menhely" type="Menhely_tipus" maxOccurs="unbounded"/>
			<xs:element name="Munkatars" type="Munkatars_tipus" maxOccurs="unbounded"/>
			<xs:element name="Dolgozik" type="Dolgozik_tipus" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Munkatars_tipus">
		<xs:sequence>
			<xs:element name="Nev" type="xs:string"/>
			<xs:element name="Email" type="xs:string" minOccurs="0"/>
			<xs:element name="Beosztas" type="xs:string"/>
			<xs:element name="Munkaido" type="Munkaido_tipus"/>
		</xs:sequence>
		<xs:attribute name="Ado_szam" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="Munkaido_tipus">
		<xs:sequence>
			<xs:element name="Tol" type="xs:positiveInteger"/>
			<xs:element name="Ig" type="xs:positiveInteger"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Allat_tipus">
		<xs:sequence>
			<xs:element name="Nev" type="xs:string"/>
			<xs:element name="Faj" type="xs:string"/>
			<xs:element name="Nem" type="xs:string"/>
			<xs:element name="Kor" type="xs:positiveInteger"/>
		</xs:sequence>
		<xs:attribute name="A_azonosito" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="Onkentes_tipus">
		<xs:sequence>
			<xs:element name="Nev" type="xs:string"/>
			<xs:element name="OnkentesOrak" type="xs:positiveInteger"/>
			<xs:element name="Email" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="Sz_szam" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="Menhely_tipus">
		<xs:sequence>
			<xs:element name="Nev" type="xs:string"/>
			<xs:element name="Telefonszam" type="xs:positiveInteger" maxOccurs="unbounded"/>
			<xs:element name="Cim" type="Cim_tipus"/>
			<xs:element name="Onkentes" type="Onkentes_tipus" maxOccurs="unbounded"/>
			<xs:element name="Allat" type="Allat_tipus" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="M_azonosito" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="Cim_tipus">
		<xs:sequence>
			<xs:element name="Iranyitoszam" type="xs:positiveInteger"/>
			<xs:element name="Varos" type="xs:string"/>
			<xs:element name="Utca" type="xs:string"/>
			<xs:element name="Hazszam" type="xs:positiveInteger"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Dolgozik_tipus">
		<xs:sequence>
			<xs:element name="Fizetes" type="xs:positiveInteger"/>
		</xs:sequence>
		<xs:attribute name="M_ref" type="xs:string"  use="required"/>
		<xs:attribute name="A_ref" type="xs:string"  use="required"/>
	</xs:complexType>
	
</xs:schema>

=== Papp-Marcell/X7A7XR_XMLGyak/XMLTaskX7A7XR/DOMParseX7A7XR/src/hu/domparse/X7A7XR/XMLX7A7XR.xml
<?xml version="1.0" encoding="UTF-8"?>

<Adatbazis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaX7A7XR.xsd">

	<Menhely M_azonosito="m1">
		<Nev>Kutya Menhely</Nev>
		<Telefonszam>1111</Telefonszam>
		<Telefonszam>2222</Telefonszam>
		<Cim>
			<Iranyitoszam>3500</Iranyitoszam>
			<Varos>Miskolc</Varos>
			<Utca>Főutca</Utca>
			<Hazszam>1</Hazszam>
		</Cim>
		
		<Onkentes Sz_szam="sz1">
			<Nev>Tamas</Nev>
			<OnkentesOrak>11</OnkentesOrak>
			<Email>Tamas@email.com</Email>
		</Onkentes>
		
		<Allat A_azonosito="a1">
			<Nev>Rex</Nev>
			<Faj>Kutya</Faj>
			<Nem>Fiú</Nem>
			<Kor>3</Kor>
		</Allat>
		
		<Allat A_azonosito="a2">
			<Nev>Cica</Nev>
			<Faj>Macska</Faj>
			<Nem>Fiú</Nem>
			<Kor>4</Kor>
		</Allat>
		
	</Menhely>
	
	<Munkatars Ado_szam="ad1">
		<Nev>Laci</Nev>
		<Email>Laci@email.com</Email>
		<Beosztas>Igazgato</Beosztas>
		<Munkaido>
			<Tol>8</Tol>
			<Ig>16</Ig>
		</Munkaido>
	</Munkatars>
	
	<Munkatars Ado_szam="ad2">
		<Nev>Pali</Nev>
		<Email>Pali@email.com</Email>
		<Beosztas>Gondnok</Beosztas>
		<Munkaido>
			<Tol>8</Tol>
			<Ig>16</Ig>
		</Munkaido>
	</Munkatars>
	
	<Dolgozik M_ref="m1" A_ref="ad1">
		<Fizetes>100000</Fizetes>
	</Dolgozik>
	
	<Dolgozik M_ref="m1" A_ref="ad2">
		<Fizetes>200000</Fizetes>
	</Dolgozik>
	
</Adatbazis>
