=== Papp-Marcell/X7A7XR_XMLGyak/X7A7XR_0928/PappMarcell_ertodtd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT root (A*,B*,C*,relAB*,relBC*)>
<!ELEMENT A (b+,Ac)>
<!ATTLIST A a ID #REQUIRED>
<!ELEMENT B (b)>
<!ATTLIST B a ID #REQUIRED>
<!ELEMENT b (x,y)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT Ac (d,e)>
<!ELEMENT d (#PCDATA)>
<!ELEMENT e (#PCDATA)>
<!ELEMENT C (Cb)>
<!ELEMENT Cb (#PCDATA)>
<!ATTLIST C a ID #REQUIRED>
<!ELEMENT relAB (c)>
<!ELEMENT c (#PCDATA)>
<!ELEMENT relBC EMPTY>
<!ATTLIST relAB Aid IDREF #REQUIRED>
<!ATTLIST relAB Bid IDREF #REQUIRED>
<!ATTLIST relBC Bid IDREF #REQUIRED>
<!ATTLIST relBC Cid IDREF #REQUIRED>

=== Papp-Marcell/X7A7XR_XMLGyak/X7A7XR_0928/PappMarcell_dtdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "PappMarcell_ertodtd.dtd">
<root>
	<A a="asd1">
		<b>
			<x>hello</x>
			<y>hello</y>
		</b>
		<Ac>
			<d>hello</d>
			<e>hello</e>
		</Ac>
	</A>
	<B a="asd2">
		<b>
			<x>hello</x>
			<y>hello</y>
		</b>
	</B>
	<C a="asd3">
		<Cb>Hello</Cb>
	</C>
	<relAB Aid="asd1" Bid="asd2">
		<c>Hello</c>
	</relAB>
	<relBC Bid="asd2" Cid="asd3"/>

</root>
