=== Papp-Marcell/X7A7XR_XMLGyak/X7A7XR_0928/X7A7XR_konyv.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT konyvek (konyv*)>
<!ELEMENT konyv (cim,kiadasiEv,szerzo+,absztrakt?)>
<!ATTLIST konyv id ID #REQUIRED>
<!ELEMENT cim (#PCDATA)>
<!ELEMENT kiadasiEv (#PCDATA)>
<!ELEMENT szerzo (#PCDATA)>
<!ELEMENT absztrakt (#PCDATA)>

=== Papp-Marcell/X7A7XR_XMLGyak/X7A7XR_0928/PappMarcell_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE konyvek SYSTEM "X7A7XR_konyv.dtd">
<konyvek>
	<konyv id="a1">
		<cim>Informatika Alapok</cim>
		<kiadasiEv>2000</kiadasiEv>
		<szerzo>Brad Pitt</szerzo>
	</konyv>
	<konyv id="a2">
		<cim>Informatika Bevezetés</cim>
		<kiadasiEv>2001</kiadasiEv>
		<szerzo>Scarlett Johanson</szerzo>
		<szerzo>Emma Stone</szerzo>
	</konyv>
	<konyv id="a3">
		<cim>Informatika Haladóknak</cim>
		<kiadasiEv>2002</kiadasiEv>
		<szerzo>Peter Parker</szerzo>
		<absztrakt>Ez egy absztrakt</absztrakt>
	</konyv>
</konyvek>
